bash run_files/extract_features/misaw_must_feats.sh
bash run_files/extract_features/heichole_must_feats.sh
bash run_files/extract_features/cholec80_must_feats.sh
bash run_files/extract_features/grasp_must_feats.sh