# Experiment setup
NUM_FRAMES=16
SAMPLE_RATE=4
TASK="CVS"
ARCH="MViT"
ONLINE=True

TRAIN_FOLD="train"
TEST_FOLD="val" 
DATASET="Endoscapes"
MAX_EPOCH=50


COCO_ANN_PATH="./data/"$DATASET"/"$DATA_TYPE"/annotations/$TEST_FOLD"_"long-term_reindex.json"
TRAIN_GT_BOX_JSON="$TRAIN_FOLD"_"long-term_reindex.json"
TEST_GT_BOX_JSON="$TEST_FOLD"_"long-term_reindex.json"
EXP_PREFIX="arch_$ARCH-frames_$NUM_FRAMES-sr_$SAMPLE_RATE-online_$ONLINE-epochs_$MAX_EPOCH"


#-------------------------
EXPERIMENT_NAME=$EXP_PREFIX"/"$TRAIN_FOLD
CONFIG_PATH="configs/"$DATASET"/"$ARCH"_"$TASK".yaml"
FRAME_DIR="./data/"$DATASET"/"$DATA_TYPE"/frames"
OUTPUT_DIR="/media/lambda001/SSD3/dlmanrique/Endovis/CVS_Challenge/Models/MuST-Challenge-CVS-2025/outputs/"$DATASET"/"$TASK"/"$EXPERIMENT_NAME
#OUTPUT_DIR="./outputs/"$DATASET"/"$TASK"/"$EXPERIMENT_NAME
FRAME_LIST="./data/"$DATASET"/"$DATA_TYPE"/frame_lists"
ANNOT_DIR="./data/"$DATASET"/"$DATA_TYPE"/annotations/"
CHECKPOINT="./model_weights/pretrained_models/K400_MVIT_B_16x4_CONV.pyth"
TYPE="pytorch"


export PYTHONPATH="./must:$PYTHONPATH"

mkdir -p $OUTPUT_DIR

CUDA_VISIBLE_DEVICES=4 python -B tools/run_net.py \
--cfg $CONFIG_PATH \
NUM_GPUS 1 \
TRAIN.DATASET $DATASET \
TEST.DATASET $DATASET \
TRAIN.CHECKPOINT_FILE_PATH $CHECKPOINT \
TRAIN.CHECKPOINT_EPOCH_RESET True \
TRAIN.CHECKPOINT_TYPE $TYPE \
TEST.ENABLE False \
TRAIN.ENABLE True \
DATA.NUM_FRAMES $NUM_FRAMES \
DATA.SAMPLING_RATE $SAMPLE_RATE \
DATA.ONLINE $ONLINE \
ENDOVIS_DATASET.FRAME_DIR $FRAME_DIR \
ENDOVIS_DATASET.FRAME_LIST_DIR $FRAME_LIST \
ENDOVIS_DATASET.TRAIN_LISTS "$TRAIN_FOLD"_"reindex.csv" \
ENDOVIS_DATASET.TEST_LISTS "$TEST_FOLD"_"reindex.csv"  \
ENDOVIS_DATASET.ANNOTATION_DIR $ANNOT_DIR \
ENDOVIS_DATASET.TEST_COCO_ANNS $COCO_ANN_PATH \
ENDOVIS_DATASET.TRAIN_GT_BOX_JSON $TRAIN_GT_BOX_JSON \
ENDOVIS_DATASET.TEST_GT_BOX_JSON $TEST_GT_BOX_JSON \
TRAIN.BATCH_SIZE 28 \
TEST.BATCH_SIZE 28 \
SOLVER.MAX_EPOCH $MAX_EPOCH \
OUTPUT_DIR $OUTPUT_DIR 